version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

volumes: 
  data: {}
  logs: {}

